# Generated by Django 3.2.13 on 2023-02-22 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('author', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('channel_id', models.BigIntegerField()),
                ('message_id', models.BigIntegerField()),
                ('document_id', models.BigIntegerField()),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
                ('name_link', models.CharField(max_length=255)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('photo', models.BooleanField()),
                ('photo_link', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('photo_thumbnail', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('photo_resize', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('public_tg', models.BooleanField(blank=True, null=True)),
                ('date_tg', models.DateTimeField(blank=True, null=True)),
                ('public_site', models.BooleanField(blank=True, null=True)),
                ('date_site', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('yadisk', models.TextField()),
                ('type_file', models.CharField(blank=True, max_length=6, null=True)),
                ('year', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['-date'],
            },
        ),
    ]
